INSERT INTO players 
(PlayerName, Position, Description, Price, Quantity, ImageName, SalePrice)
VALUES 
("David De Gea", "GK", "Goalkeeper for Man Utd", 5.6, 5, "images/manutd.png", 0.0),
("Petr Cech", "GK", "Goalkeeper for Arsenal", 5.5, 5, "images/arsenal.png", 0.0),
("Thibaut Courtois", "GK", "Goalkeeper for Chelsea", 5.5, 5, "images/chelsea.png", 0.0),
("Lukas Fabianksi", "GK", "Goalkeeper for Swansea", 4.5, 5, "images/swansea.png", 0.0),
("Joe Hart", "GK", "Goalkeeper for West Ham", 4.5, 5, "images/westham.png", 4.0),
("Simon Mignolet", "GK", "Goalkeeper for Liverpool", 4.9, 5, "images/liverpool.png", 0.0),
("Hugo Lloris", "GK", "Goalkeeper for Spurs", 5.5, 5, "images/spurs.png", 0.0),
("Fraser Forster", "GK", "Goalkeeper for Southampton", 5.0, 5, "images/southampton.png", 0.0),
("Marcos Alonso", "DEF", "Defender for Chelsea", 7.0, 5, "images/chelsea.png", 0.0),
("Kyle Walker", "DEF", "Defender for Man City ", 6.5, 5, "images/mancity.png", 0.0),
("Danny Rose", "DEF", "Defender for Spurs", 6.4, 5, "images/spurs.png", 5.0),
("James Milner", "DEF", "Defender for Liverpool", 6.2, 5, "images/liverpool.png", 0.0),
("Laurent Koscielny", "DEF", "Defender for Arsenal", 6.0, 5, "images/arsenal.png", 0.0),
("Sead Kolasinac","DEF",  "Defender for Arsenal", 6.0, 5, "images/arsenal.png", 0.0),
("Leighton Baines", "DEF", "Defender for Everton", 5.9, 5, "images/everton.png", 0.0),
("Kieran Gibbs", "DEF", "Defender for West Brom", 5.0, 5, "images/westbrom.png", 0.0),
("Kevin De Bruyne", "MID", "Midfielder for Man City", 10.0, 5, "images/mancity.png", 0.0),
("Christian Eriksen", "MID", "Midfielder for Spurs", 9.7, 5, "images/spurs.png", 0.0),
("Mesut Ozil", "MID", "Midfielder for Arsenal", 9.4, 5, "images/arsenal.png", 7.0),
("Mohammed Salah", "MID", "Midfielder for Liverpool", 9.2, 5, "images/liverpool.png", 0.0),
("Riyhad Mahrez", "MID", "Midfielder for Leicester", 8.5, 5, "images/leicester.png", 0.0),
("Gylfi Sigurdsson", "MID", "Midfielder for Everton", 8.2, 5, "images/everton.png", 0.0),
("Wilfreid Zaha", "MID", "Midfielder for Crystal Palace", 6.7, 5, "images/crystalpalace.png", 0.0),
("Dusan Tadic", "MID", "Midfielder for Southampton", 6.5, 5, "images/southampton.png", 0.0),
("Alexis Sanchez", "FWD", "Forward for Arsenal", 11.9, 5, "images/arsenal.png", 0.0),
("Harry Kane", "FWD", "Forward for Spurs", 12.7, 5, "images/spurs.png", 0.0),
("Romeleu Lukaku", "FWD", "Forward for Man Utd", 11.8, 5, "images/manutd.png", 0.0),
("Gabriel Jesus", "FWD", "Forward for Man City", 10.5, 5, "images/mancity.png", 0.0),
("Zlatan Ibrahimovic", "FWD", "Forward for Man Utd", 10.0, 5, "images/manutd.png", 0.0),
("Chicharito", "FWD", "Forward for West Ham", 7.0, 5, "images/westham.png", 0.0),
("Dwight Gayle", "FWD", "Forward for Newcastle", 6.2, 5, "images/newcastle.png", 0.0),
("Troy Deeney", "FWD", "Forward for Watford", 6.4, 5, "images/watford.png", 0.0)
;
